// <auto-generated />
using System;
using KassenzettelApi.DB_Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KassenzettelApi.Migrations
{
    [DbContext(typeof(KassenzettelDbContext))]
    [Migration("20231013084542_newRelations")]
    partial class newRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KassenzettelApi.Classes.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nutzername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("KassenzettelApi.Classes.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("KassenzettelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KassenzettelId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("KassenzettelApi.Classes.Kassenzettel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Shop")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("KassenzettelApi.Classes.Item", b =>
                {
                    b.HasOne("KassenzettelApi.Classes.Kassenzettel", null)
                        .WithMany("Items")
                        .HasForeignKey("KassenzettelId");
                });

            modelBuilder.Entity("KassenzettelApi.Classes.Kassenzettel", b =>
                {
                    b.HasOne("KassenzettelApi.Classes.Customer", null)
                        .WithMany("Kassenzettel")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("KassenzettelApi.Classes.Customer", b =>
                {
                    b.Navigation("Kassenzettel");
                });

            modelBuilder.Entity("KassenzettelApi.Classes.Kassenzettel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
